// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Always use direct connection for CLI — pooler breaks migrations.
    // Falls back gracefully to DATABASE_URL or a mock string to prevent build crashes when env vars are absent.
    url: process.env.DIRECT_URL || process.env.DATABASE_URL || "postgresql://mock-url-for-build-time",
  },
});
